baseURL = 'https://willgibson.github.io/willgibson.co.uk/'
languageCode = 'en-gb'
title = 'Will Gibson AKA Walter Ego'
theme = 'ananke'
publishDir = "docs"
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/willgibson.co.uk/home/"
        weight = 1
    [[menu.main]]
        identifier = "devops-software-engineer"
        name = "DevOps Software Engineer"
        url = "/willgibson.co.uk/devops-software-engineer/"
        weight = 2
    [[menu.main]]
        identifier = "musician-producer"
        name = "Musician Producer"
        url = "/willgibson.co.uk/musician-producer/"
        weight = 3
    [[menu.main]]
        identifier = "jugaads"
        name = "Jugaads"
        url = "/willgibson.co.uk/jugaads/"
        weight = 4
